"""Genera la migracion 0002 (las 50 tablas) desde el metadata, sin base de datos.

Alembic normalmente hace esto con `flask db migrate`, pero eso exige conectarse
a la base para comparar. Aqui se produce el mismo resultado offline, lo que
permite revisar y verificar la migracion ANTES de tocar PostgreSQL.

Las tres claves foraneas marcadas con use_alter se sacan de sus CREATE TABLE y
se agregan al final con create_foreign_key: son los tres ciclos del esquema
(users<->parties, parties<->price_lists, batches<->purchase_items) y de otro
modo no habria orden de creacion posible.

Uso:
    python generar_migracion_inicial.py
"""
from __future__ import annotations

import sys
from pathlib import Path

AQUI = Path(__file__).resolve().parent
sys.path.insert(0, str(AQUI))

from alembic.autogenerate import api
from alembic.migration import MigrationContext
from alembic.operations import ops

from app.models import Base

SALIDA = AQUI / "migrations" / "versions" / "0002_esquema_inicial.py"
REVISION = "0002_esquema_inicial"
ANTERIOR = "0001_extensiones"

PLANTILLA = '''"""Esquema inicial: las 50 tablas del ERD logico v1.0.

Generada desde app/models con generar_migracion_inicial.py, no a mano.
Para regenerarla: borra este archivo y vuelve a correr ese script.

Las tres claves foraneas del final cierran los ciclos del esquema y por eso van
separadas del CREATE TABLE:
  users.party_id -> parties
  parties.default_price_list_id -> price_lists
  batches.purchase_item_id -> purchase_items

Revision ID: {rev}
Revises: {prev}
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
{imports}

revision = "{rev}"
down_revision = "{prev}"
branch_labels = None
depends_on = None

# Las tres FK que cierran ciclos: se crean despues de todas las tablas y se
# eliminan antes de todas ellas.
FK_CICLICAS = [
{fks_lista}
]


def upgrade() -> None:
{cuerpo_up}

    for nombre, tabla, refiere, col, refcol, ondelete in FK_CICLICAS:
        op.create_foreign_key(nombre, tabla, refiere, [col], [refcol],
                              ondelete=ondelete)


def downgrade() -> None:
    for nombre, tabla, *_ in FK_CICLICAS:
        op.drop_constraint(nombre, tabla, type_="foreignkey")

{cuerpo_down}
'''


def main() -> int:
    md = Base.metadata

    # 1. Separar las FK que cierran ciclos ---------------------------------
    ciclicas = []
    for t in md.tables.values():
        for c in list(t.constraints):
            if not hasattr(c, "elements") or not c.elements:
                continue
            fk = c.elements[0]
            if getattr(fk, "use_alter", False) or getattr(c, "use_alter", False):
                ciclicas.append((
                    c.name, t.name, fk.column.table.name,
                    fk.parent.name, fk.column.name, fk.ondelete,
                ))
                t.constraints.discard(c)
                fk.parent.foreign_keys.discard(fk)
    ciclicas.sort()
    if len(ciclicas) != 3:
        print(f"[ERROR] Se esperaban 3 FK ciclicas, se hallaron {len(ciclicas)}:")
        for c in ciclicas:
            print("   ", c)
        return 1
    print(f"[OK] {len(ciclicas)} FK ciclicas separadas:")
    for n, t, r, *_ in ciclicas:
        print(f"     {t} -> {r}  ({n})")

    # 2. Construir las operaciones en orden topologico ---------------------
    mc = MigrationContext.configure(dialect_name="postgresql", opts={
        "sqlalchemy_module_prefix": "sa.",
        "alembic_module_prefix": "op.",
        "target_metadata": md,
    })

    up: list = []
    for t in md.sorted_tables:
        up.append(ops.CreateTableOp.from_table(t))
        for idx in sorted(t.indexes, key=lambda i: i.name or ""):
            up.append(ops.CreateIndexOp.from_index(idx))

    down: list = []
    for t in reversed(md.sorted_tables):
        for idx in sorted(t.indexes, key=lambda i: i.name or ""):
            down.append(ops.DropIndexOp.from_index(idx))
        down.append(ops.DropTableOp.from_table(t))

    def limpiar(texto: str) -> str:
        """Quita los marcadores de plantilla de Alembic y normaliza la sangria.

        El "please adjust!" que inserta Alembic es enganoso aqui: esta migracion
        se genera desde el metadata, no se ajusta a mano.
        """
        fuera = []
        for linea in texto.splitlines():
            if "commands auto generated by Alembic" in linea:
                continue
            if "end Alembic commands" in linea:
                continue
            fuera.append(("    " + linea.lstrip()) if linea.strip() else "")
        return "\n".join(fuera).strip("\n")

    cuerpo_up = limpiar(api.render_python_code(
        ops.UpgradeOps(ops=up), migration_context=mc))
    cuerpo_down = limpiar(api.render_python_code(
        ops.DowngradeOps(ops=down), migration_context=mc))

    # render_python_code no expone los imports que hizo falta, asi que se
    # deducen del texto: si aparece el prefijo, el import es obligatorio.
    necesarios = set()
    if "postgresql." in cuerpo_up or "postgresql." in cuerpo_down:
        necesarios.add("from sqlalchemy.dialects import postgresql")
    imports = "\n".join(sorted(necesarios))
    fks_lista = "\n".join(
        f"    ({n!r}, {t!r}, {r!r}, {c!r}, {rc!r}, {od!r}),"
        for n, t, r, c, rc, od in ciclicas
    )

    SALIDA.parent.mkdir(parents=True, exist_ok=True)
    SALIDA.write_text(PLANTILLA.format(
        rev=REVISION, prev=ANTERIOR, imports=imports,
        fks_lista=fks_lista, cuerpo_up=cuerpo_up, cuerpo_down=cuerpo_down,
    ), encoding="utf-8")

    # 3. Verificar lo generado --------------------------------------------
    txt = SALIDA.read_text(encoding="utf-8")
    # Se verifica cada mitad por separado: un conteo global esconderia que a
    # downgrade le falte algo que upgrade si tiene.
    cuerpo, _, mitad_down = txt.partition("def downgrade()")
    n_idx = sum(len(t.indexes) for t in md.tables.values())
    esperado = [
        ("upgrade",   cuerpo,     "op.create_table(", 50),
        ("upgrade",   cuerpo,     "op.create_index(", n_idx),
        ("upgrade",   cuerpo,     "postgresql.ExcludeConstraint(", 2),
        ("upgrade",   cuerpo,     "postgresql_where=", 8),
        ("downgrade", mitad_down, "op.drop_table(", 50),
        ("downgrade", mitad_down, "op.drop_index(", n_idx),
    ]
    print(f"\n[OK] Migracion escrita: {SALIDA.relative_to(AQUI)} "
          f"({len(txt.splitlines())} lineas)")
    fallo = False
    for mitad, texto, aguja, n in esperado:
        real = texto.count(aguja)
        if real != n:
            fallo = True
        print(f"  [{'OK ' if real == n else 'MAL'}] {mitad:9} {aguja:32} "
              f"{real:>3} (esperado {n})")

    if "from sqlalchemy.dialects import postgresql" not in txt:
        print("  [MAL] falta el import de postgresql, "
              "las EXCLUDE no compilarian")
        fallo = True
    else:
        print("  [OK ] import de postgresql presente")

    import ast
    try:
        ast.parse(txt)
        print("  [OK ] el archivo es Python valido")
    except SyntaxError as e:
        print(f"  [MAL] error de sintaxis en linea {e.lineno}: {e.msg}")
        fallo = True

    if fallo:
        print("\nGENERACION CON PROBLEMAS: revisa el archivo antes de aplicarlo.")
        return 1
    print("\nMIGRACION GENERADA Y VERIFICADA.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
