"""Agrega costos no inventariables de producción

Revision ID: 97dc605d3d64
Revises: 0003_telegram_comprobantes
Create Date: 2026-09-28 16:31:36.084551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dc605d3d64'
down_revision = '0003_telegram_comprobantes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_costs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.BigInteger(), nullable=False),
    sa.Column('process_execution_id', sa.BigInteger(), nullable=True),
    sa.Column('cost_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default='COP', nullable=False),
    sa.Column('supplier_party_id', sa.BigInteger(), nullable=True),
    sa.Column('supplier_document_number', sa.String(length=40), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cost_type IN ('ENERGY', 'LABOR', 'OTHER', 'QUALITY_CONTROL', 'TRANSPORT')", name=op.f('ck_production_costs_cost_type_valid')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_production_costs_amount_positive')),
    sa.ForeignKeyConstraint(['process_execution_id'], ['process_executions.id'], name=op.f('fk_production_costs_process_execution_id_process_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], name=op.f('fk_production_costs_production_order_id_production_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_party_id'], ['parties.id'], name=op.f('fk_production_costs_supplier_party_id_parties'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_costs'))
    )
    with op.batch_alter_table('production_costs', schema=None) as batch_op:
        batch_op.create_index('ix_production_costs_execution', ['process_execution_id'], unique=False)
        batch_op.create_index('ix_production_costs_order', ['production_order_id'], unique=False)
        batch_op.create_index('ix_production_costs_type', ['cost_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_costs', schema=None) as batch_op:
        batch_op.drop_index('ix_production_costs_type')
        batch_op.drop_index('ix_production_costs_order')
        batch_op.drop_index('ix_production_costs_execution')

    op.drop_table('production_costs')
    # ### end Alembic commands ###
